# _config.yml
title: Michael.Krzyzanski
description: Beratung- und Auditorentätigkeiten rund um die Informationssicherheit
url: "https://megatraveller.github.io" # die URL deiner Website
baseurl: "" # der Basispfad deiner Website, normalerweise ""

# E-Mail und Autor Informationen (optional)
email: michael@krzyzanski.de
author: Michael Krzyzanski

# Jekyll und Plugin Einstellungen
markdown: kramdown
# theme: jekyll-theme-yat
# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
remote_theme: "jeffreytse/jekyll-theme-yat"

# Build Einstellungen
exclude:
  - Gemfile
  - Gemfile.lock

# Weitere Konfigurationen können hier hinzugefügt werden, je nach den spezifischen Anforderungen deiner Website.
plugins:
  - jekyll-feed

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - archives.html
  - categories.html
  - tags.html
  - about.md
